### PR TITLE
Fix bug

### PR DESCRIPTION
**Pull request by mqklin**

### CODE REVIEW

**Comment by haydenadams** [comment]
its `(numerator / denominator) + 1 `

**Comment by mqklin** [comment]
@haydenadams I think you are wrong: https://github.com/Uniswap/uniswap-frontend/blob/03ecca1b5e6d05b43d7d49be2a57cf5326c65331/src/pages/Send/index.js#L815
Can you reopen PR? Or should I create a new one?

**Comment by haydenadams** [comment]
ooh thats a frontend bug, good catch! 

The smart contract has the proper implementation: 
https://github.com/Uniswap/contracts-vyper/blob/master/contracts/uniswap_exchange.vy#L124

**Comment by mqklin** [comment]
Are you sure? Frontend implementation seems correct (rates are almost the same as at coinmarketcap)

**Comment by haydenadams** [comment]
Yes, no matter what the frontend says, the rate you will get is based on the smart contract implementation. 

For most trades the difference between the two calculations is likely less than a penny, which is why no one has noticed until now :)

**Comment by mqklin** [comment]
I see, thank you for the explanation. 
Are other calculations in the docs correct? Can you check it please?

**Pull request closed without merging**
